#!/usr/bin/env python3
"""Build a private Content Quality runtime env without printing credentials."""

from __future__ import annotations

import argparse
import secrets
import shlex
from pathlib import Path

from dotenv import dotenv_values


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--credential-env", type=Path)
    args = parser.parse_args()

    output = args.output.expanduser().resolve()
    existing = dotenv_values(output) if output.is_file() else {}
    credential_path = (
        args.credential_env.expanduser().resolve()
        if args.credential_env is not None else None
    )
    if credential_path is not None:
        if not credential_path.is_file():
            raise SystemExit(f"credential env does not exist: {credential_path}")
        credential_values = dotenv_values(credential_path)
        if not str(credential_values.get("OPENAI_API_KEY") or "").strip():
            raise SystemExit("credential env does not contain OPENAI_API_KEY")

    values = {
        "CONTENT_QUALITY_CONTROL_TOKEN": (
            str(existing.get("CONTENT_QUALITY_CONTROL_TOKEN") or "").strip()
            or secrets.token_urlsafe(48)
        ),
        "NARRATIVE_COHERENCE_LLM": "openai",
        "NARRATIVE_JUDGE_MODEL": "gpt-5-nano",
        "TRANSCRIPT_BANK_ROOT": "/Volumes/My Passport/MarketTape/transcript-bank",
    }
    if credential_path is not None:
        values["CONTENT_QUALITY_CREDENTIAL_ENV_FILE"] = str(credential_path)
    elif existing.get("CONTENT_QUALITY_CREDENTIAL_ENV_FILE"):
        values["CONTENT_QUALITY_CREDENTIAL_ENV_FILE"] = str(
            existing["CONTENT_QUALITY_CREDENTIAL_ENV_FILE"]
        )

    lines = [
        "# Generated by build_content_quality_runtime_env.py; chmod 600; never commit.",
        *(f"export {name}={shlex.quote(value)}" for name, value in sorted(values.items())),
        "",
    ]
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_suffix(output.suffix + ".tmp")
    temporary.write_text("\n".join(lines), encoding="utf-8")
    temporary.chmod(0o600)
    temporary.replace(output)
    output.chmod(0o600)
    print(
        "Content Quality runtime configuration written; "
        f"credential source configured={bool(values.get('CONTENT_QUALITY_CREDENTIAL_ENV_FILE'))}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
