#!/usr/bin/env python3
"""Build a minimal private runtime environment without printing secret values."""

from __future__ import annotations

import argparse
import os
import secrets
import shlex
from pathlib import Path

from dotenv import load_dotenv


PROVIDER_NAMES = {
    "ANTHROPIC_API_KEY",
    "FACEBOOK_ACCESS_TOKEN",
    "FACEBOOK_PAGE_ID",
    "GROQ_API_KEY",
    "INSTAGRAM_ACCESS_TOKEN",
    "INSTAGRAM_ACCOUNT_ID",
    "INSTAGRAM_BUSINESS_ACCOUNT_ID",
    "MARKET_RESEARCH_URL",
    "META_ACCESS_TOKEN",
    "OPENAI_API_KEY",
    "RAPIDAPI_KEY",
    "RESEARCH_API_KEY",
    "SUPABASE_SERVICE_KEY",
    "SUPABASE_SERVICE_ROLE_KEY",
    "SUPABASE_URL",
    "THREADS_ACCESS_TOKEN",
    "THREADS_ACCOUNT_ID",
    "THREADS_USER_ID",
    "TIKTOK_CLIENT_KEY",
    "TIKTOK_CLIENT_SECRET",
    "TIKTOK_RESEARCH_ACCESS_TOKEN",
    "TWITTER_BEARER_TOKEN",
    "X_BEARER_TOKEN",
    "YOUTUBE_API_KEY",
    "YOUTUBE_DATA_API_KEY",
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, required=True)
    parser.add_argument("--runtime-base", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--rotate-control-token", action="store_true")
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    runtime_base = args.runtime_base.expanduser().resolve()
    # Market Tape owns its runtime configuration. Preserve its last private
    # allowlisted environment first, then fill missing values from this repo.
    # Do not create a hidden runtime dependency on ACTP or any other service.
    for path in (
        args.output.expanduser(),
        repo_root / ".env",
        repo_root / ".env.production",
        repo_root / ".env.market-tape",
    ):
        if path.is_file():
            load_dotenv(path, override=False)

    values = {
        name: value
        for name, value in os.environ.items()
        if value and (name.startswith("MARKET_TAPE_") or name in PROVIDER_NAMES)
    }
    values["MARKET_TAPE_CONTROL_TOKEN"] = (
        secrets.token_urlsafe(48)
        if args.rotate_control_token
        else (
            str(values.get("MARKET_TAPE_CONTROL_TOKEN") or "").strip()
            or secrets.token_urlsafe(48)
        )
    )
    if not values.get("INSTAGRAM_BUSINESS_ACCOUNT_ID"):
        values["INSTAGRAM_BUSINESS_ACCOUNT_ID"] = values.get("INSTAGRAM_ACCOUNT_ID", "")
    if not values.get("THREADS_USER_ID"):
        values["THREADS_USER_ID"] = values.get("THREADS_ACCOUNT_ID", "")

    data_dir = runtime_base / "data"
    values.update({
        "MARKET_TAPE_DB_PATH": str(data_dir / "market-tape.sqlite3"),
        "MARKET_TAPE_OBJECT_DIR": str(data_dir / "market-tape-objects"),
        "MARKET_TAPE_HEARTBEAT_PATH": str(data_dir / "market-tape-heartbeat.json"),
        "MARKET_TAPE_LOCK_PATH": str(data_dir / "market-tape.lock"),
        "MARKET_TAPE_LOCAL_RESEARCH_STATE_PATH": str(
            data_dir / "market-tape-local-research-state.json"
        ),
        "MARKET_TAPE_PREDICTION_MODEL_DIR": str(data_dir / "market-tape-models"),
        "MARKET_TAPE_LOCAL_RESEARCH_DIR": str(
            Path.home() / "Library" / "Application Support" / "SafariAutomation" / "market-research-data"
        ),
        "MARKET_TAPE_PASSPORT_MOUNT": "/Volumes/My Passport",
        "MARKET_TAPE_DATASET_ROOT": "/Volumes/My Passport/MarketTape/datasets",
        "MARKET_TAPE_YOUTUBE_RESEARCH_DIR": "/Volumes/My Passport/MarketTape/trend-frontier",
        "MARKET_TAPE_DATASET_EXPORT_ENABLED": "true",
        "MARKET_TAPE_DATASET_REQUIRE_MOUNTED_VOLUME": "true",
        "MARKET_TAPE_DATASET_STORAGE_PREFLIGHT_TIMEOUT_SECONDS": "30",
    })

    lines = [
        "# Generated by build_market_tape_runtime_env.py; chmod 600; never commit.",
        *(f"export {name}={shlex.quote(value)}" for name, value in sorted(values.items()) if value),
        "",
    ]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    temporary = args.output.with_suffix(".tmp")
    temporary.write_text("\n".join(lines), encoding="utf-8")
    temporary.chmod(0o600)
    temporary.replace(args.output)
    args.output.chmod(0o600)
    print(f"Wrote {len(lines) - 2} allowlisted runtime variables to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
